// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaBuAeY8ih_EY2A5tGlwvRgWAhhjM8s2A',
    appId: '1:323682521450:web:5320e549234e0ee3d91513',
    messagingSenderId: '323682521450',
    projectId: 'testing-a4e4f',
    authDomain: 'testing-a4e4f.firebaseapp.com',
    storageBucket: 'testing-a4e4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9N7yxRsycgnkow7iYhyaDd5HfZjjTerM',
    appId: '1:323682521450:android:9ae801a6c3fa649dd91513',
    messagingSenderId: '323682521450',
    projectId: 'testing-a4e4f',
    storageBucket: 'testing-a4e4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7yV3eKGGvMucR_clSqGKk-Jn-baTHRjE',
    appId: '1:323682521450:ios:8dd94a06405cc500d91513',
    messagingSenderId: '323682521450',
    projectId: 'testing-a4e4f',
    storageBucket: 'testing-a4e4f.appspot.com',
    iosClientId: '323682521450-etvnm2jrqs022dj97jnkoo2mq69247uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.proto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7yV3eKGGvMucR_clSqGKk-Jn-baTHRjE',
    appId: '1:323682521450:ios:715306793998200cd91513',
    messagingSenderId: '323682521450',
    projectId: 'testing-a4e4f',
    storageBucket: 'testing-a4e4f.appspot.com',
    iosClientId: '323682521450-ugr2clj938mdv5e6q5j8gclhpamt0ft3.apps.googleusercontent.com',
    iosBundleId: 'com.example.proto.RunnerTests',
  );
}
