// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBArSO6ZbGnne-pvmnDOx8nMLzOXonuFaQ',
    appId: '1:404671123467:web:68c2233981eff65a53f70e',
    messagingSenderId: '404671123467',
    projectId: 'proto-93114',
    authDomain: 'proto-93114.firebaseapp.com',
    storageBucket: 'proto-93114.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9fHXRL3gyXwcNcTwHfmSWpD4U5eD72Ks',
    appId: '1:404671123467:android:355768a5e8f56c6953f70e',
    messagingSenderId: '404671123467',
    projectId: 'proto-93114',
    storageBucket: 'proto-93114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdSeJCu_8F-nI0GXv1ECuSDITkZhF_KdE',
    appId: '1:404671123467:ios:ff49835e2386c51653f70e',
    messagingSenderId: '404671123467',
    projectId: 'proto-93114',
    storageBucket: 'proto-93114.appspot.com',
    iosBundleId: 'com.example.proto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdSeJCu_8F-nI0GXv1ECuSDITkZhF_KdE',
    appId: '1:404671123467:ios:6ef95e2857e9349253f70e',
    messagingSenderId: '404671123467',
    projectId: 'proto-93114',
    storageBucket: 'proto-93114.appspot.com',
    iosBundleId: 'com.example.proto.RunnerTests',
  );
}
